import React from "react"
import Link from "next/link"
import Head from "next/head"
import Image from "next/image"
import styles from "./styles.module.css"
import { Navbar } from "../menu/navbar"

export function Header() {
  return (
    <>
      <Head>
        <title>Run Engine</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/run-engine-favicon.ico' />
      </Head>
      <header className={styles.header}>
        <Link href='/'>
          <h1>Run engine</h1>
        </Link>
        <Navbar />
        <Image
          src='/Images/run-engine-logo.png'
          alt='run engine calcul de vitesse'
          width={300}
          height={300}
        />
      </header>
    </>
  )
}
